# 補充文案：每段嘅詳細說明、「點開始」三步、常見問題
E = {}
E['zh-HK'] = dict(
  badge_apple='apple-zh-hk.svg', badge_google='google-zh-tw.png',
  p_lead='電話、訊息、紙本，三頭六臂都應付唔到。以下三件事，幾乎每間一人或兩人經營嘅店都遇過。',
  s_lead='客人自己揀時間，店主唔使再喺服務途中停低手。所有渠道嘅預約，最後都落喺同一個日曆度。',
  d_extra='舉個例：星期二下午三點通常都做得切，就設成即時確認；星期六夜晚係黃金時段，想自己揀客就設成要審批。同一間店，唔同時段唔同規則。',
  w_lead='只要生意係「客人約時間上嚟」，呢套流程就啱用。以下係已經用得上嘅行業，其他類似模式嘅店都一樣得。',
  st_chip='點開始', st_h2='三步就收到第一個預約',
  st_items=[('登記做商戶','用電郵開個帳戶，揀返你間店嘅行業同所在地。'),
            ('入服務同營業時間','每項服務寫低時長同價錢，再設返每日營業時間；休息日同保留時段都可以隨時改。'),
            ('派 QR 卡或連結俾客人','系統即刻生成可列印嘅 QR 卡同預約連結，貼喺店內、放落社交平台或者印上名片。')],
  faq_chip='常見問題', faq_h2='你可能想問',
  faq=[('客人要唔要裝 App 先約到？','唔使。客人撳你條連結或者掃 QR 卡，用瀏覽器就可以直接預約，毋須安裝，亦毋須開戶口。網頁預約一律要你確認先成立；已經裝咗 App 嘅客人會直接喺 App 開。'),
       ('我可以自己代客人落單嗎？','可以。電話單同上門單都入得，同網上預約一樣入同一個日曆，會計入統計同客戶紀錄。'),
       ('客人臨時改時間點算？','客人同店主都可以改期，唔使取消再重新預約，原本嗰張單保留住，方便你睇返實際情況。'),
       ('會唔會抽佣或者經手客人嘅錢？','唔會。客人係直接俾錢你間店，我哋唔經手任何款項，所以亦冇佣金。'),
       ('已經喺其他預約平台上架，仲用得嗎？','用得。平台幫你招新客，BookingYou 幫你管理所有預約（包括熟客），兩者可以並行。')],
  dl_note='下載完，用電郵登記就可以開始設定。',
)
E['en'] = dict(
  badge_apple='apple-en-us.svg', badge_google='google-en.png',
  p_lead='Phone, messages and a paper book at the same time. These three things happen in almost every shop run by one or two people.',
  s_lead='Customers pick their own time, so you never stop mid-treatment to answer the phone. Bookings from every channel land in one calendar.',
  d_extra='For example: Tuesday at 3pm is usually easy to fit in, so it confirms instantly. Saturday evening is your busiest slot, so it waits for your approval. Same shop, different rules by hour.',
  w_lead='If your work is "customers book a time and come in", this flow fits. These are the categories already in use; shops with a similar rhythm work the same way.',
  st_chip='Getting started', st_h2='Three steps to your first booking',
  st_items=[('Register as a merchant','Create an account with your email, then pick your category and location.'),
            ('Add services and opening hours','Give each service a duration and price, set your weekly hours, and adjust closed days or reserved slots any time.'),
            ('Share your QR card or link','A printable QR card and booking link are generated right away — put them on the counter, in your social profile or on a business card.')],
  faq_chip='FAQ', faq_h2='You might be wondering',
  faq=[('Does the customer need the app to book?','No. Customers tap your link or scan your QR card and book right in the browser — no install and no account. Every web booking waits for your confirmation, and customers who already have the app go straight into it.'),
       ('Can I enter a booking for a customer myself?','Yes. Phone and walk-in bookings go into the same calendar as online ones, and they count in your statistics and customer records.'),
       ('What if a customer needs a different time?','Both sides can reschedule without cancelling, so the original booking stays intact and your numbers stay honest.'),
       ('Do you take a commission or hold my money?','No. Customers pay your shop directly. We never handle the money, so there is no commission.'),
       ('I already list on a booking portal. Can I still use this?','Yes. Portals bring new customers; BookingYou runs every booking including your regulars. They work side by side.')],
  dl_note='Download it, sign up with your email, and you can start setting up.',
)
E['zh-CN'] = dict(
  badge_apple='apple-zh-cn.svg', badge_google='google-zh-cn.png',
  p_lead='电话、消息、纸质记录同时来，一两个人的小店根本分身乏术。下面三件事，几乎每家都遇到过。',
  s_lead='客人自己选时间，店主不用在服务途中停下来接电话。所有渠道的预约，最后都落在同一个日历里。',
  d_extra='举个例子：周二下午三点通常做得过来，就设成即时确认；周六晚上是黄金时段，想自己挑客就设成需要审核。同一家店，不同时段不同规则。',
  w_lead='只要生意是「客人约时间上门」，这套流程就适用。以下是已经在用的行业，其他类似模式的店同样可以。',
  st_chip='如何开始', st_h2='三步收到第一个预约',
  st_items=[('注册成为商户','用邮箱开通账户，选择行业和所在地。'),
            ('录入服务和营业时间','每项服务填写时长和价格，设置每周营业时间；休息日和保留时段随时可改。'),
            ('把二维码卡或链接给客人','系统立即生成可打印的二维码卡和预约链接，贴在店内、放到社交平台或印在名片上。')],
  faq_chip='常见问题', faq_h2='你可能想问',
  faq=[('客人需要安装 App 才能预约吗？','不需要。客人点击你的链接或扫描二维码卡，用浏览器就能直接预约，无需安装，也无需注册账号。网页预约都要你确认后才成立；已安装 App 的客人会直接在 App 中打开。'),
       ('我可以替客人下单吗？','可以。电话和到店的预约都能录入，与线上预约进入同一个日历，并计入统计和客户记录。'),
       ('客人临时要改时间怎么办？','双方都可以改期，无需取消后重新预约，原订单保留，方便你看清真实情况。'),
       ('会抽成或经手客人的钱吗？','不会。客人直接付款给店铺，我们不经手任何款项，因此没有佣金。'),
       ('已经在其他预约平台上架，还能用吗？','可以。平台帮你招揽新客，BookingYou 帮你管理所有预约（包括老客户），两者并行不冲突。')],
  dl_note='下载后用邮箱注册，就可以开始设置。',
)
E['ja'] = dict(
  badge_apple='apple-ja-jp.svg', badge_google='google-ja.png',
  p_lead='電話、メッセージ、紙の台帳が同時に来ます。一人か二人で営むお店なら、次の3つはほぼ必ず経験します。',
  s_lead='お客様がご自身で時間を選ぶので、施術の途中で手を止める必要がありません。どの経路の予約も、最後は同じカレンダーに集まります。',
  d_extra='たとえば、火曜の15時はたいてい対応できるので即時確定に。土曜の夜は繁忙時間なので、オーナーの承認を挟む。同じ店舗でも、時間帯ごとにルールを変えられます。',
  w_lead='「お客様が時間を予約して来店する」商売であれば、この流れがそのまま使えます。以下はすでに使われている業種で、似た形態のお店でも同様です。',
  st_chip='はじめ方', st_h2='3ステップで最初の予約を受ける',
  st_items=[('店舗として登録','メールアドレスでアカウントを作成し、業種と所在地を選びます。'),
            ('メニューと営業時間を登録','各メニューに所要時間と料金を設定し、曜日ごとの営業時間を登録。定休日や確保したい時間帯はいつでも変更できます。'),
            ('QRカードやリンクをお客様へ','印刷用のQRカードと予約リンクがすぐに生成されます。店頭に貼る、SNSに載せる、名刺に印刷する、どれでも使えます。')],
  faq_chip='よくある質問', faq_h2='よくいただく質問',
  faq=[('お客様はアプリのインストールが必要ですか？','いいえ、不要です。お客様はリンクをひらくか QR カードを読み取るだけで、ブラウザからそのまま予約できます。インストールもアカウント登録も不要です。ウェブ予約はすべてお店の確認後に確定し、アプリをお持ちのお客様はそのままアプリでひらきます。'),
       ('店舗側で代理予約はできますか？','できます。電話や来店の予約もネット予約と同じカレンダーに入り、統計や顧客記録にも反映されます。'),
       ('お客様が時間を変更したいときは？','お客様も店舗も、キャンセルせずに日時変更ができます。元の予約が残るため、実態が数字に正しく残ります。'),
       ('手数料や決済の預かりはありますか？','ありません。お客様はお店に直接お支払いいただくため、当社が資金を扱うことはなく、手数料も発生しません。'),
       ('すでに予約サイトに掲載していますが、併用できますか？','できます。予約サイトは新規のお客様、BookingYouは常連を含むすべての予約の管理。役割が違うので併用できます。')],
  dl_note='ダウンロード後、メールアドレスで登録すれば設定を始められます。',
)

E['ko'] = dict(
  badge_apple='apple-ko-kr.svg', badge_google='google-ko.png',
  p_lead='전화, 메시지, 종이 장부가 한꺼번에 몰립니다. 한두 명이 운영하는 매장이라면 아래 세 가지는 거의 반드시 겪습니다.',
  s_lead='고객이 직접 시간을 고르기 때문에 시술 도중에 손을 멈출 일이 없습니다. 모든 경로의 예약이 하나의 캘린더에 모입니다.',
  d_extra='예를 들어 화요일 오후 3시는 대체로 여유가 있으니 즉시 확정으로, 토요일 저녁은 가장 바쁜 시간이니 사장님 승인 후 확정으로. 같은 매장이라도 시간대마다 규칙을 다르게 둘 수 있습니다.',
  w_lead='"고객이 시간을 예약하고 방문하는" 형태라면 이 흐름이 그대로 맞습니다. 아래는 이미 사용 중인 업종이며, 비슷한 방식의 매장도 동일합니다.',
  st_chip='시작하기', st_h2='세 단계면 첫 예약을 받습니다',
  st_items=[('매장으로 가입','이메일로 계정을 만들고 업종과 위치를 선택합니다.'),
            ('서비스와 영업시간 입력','서비스마다 소요 시간과 가격을 넣고 요일별 영업시간을 설정합니다. 휴무일과 확보 시간대는 언제든 변경할 수 있습니다.'),
            ('QR 카드나 링크를 고객에게','인쇄용 QR 카드와 예약 링크가 바로 생성됩니다. 매장에 붙이거나 SNS 프로필, 명함에 넣어 사용하세요.')],
  faq_chip='자주 묻는 질문', faq_h2='궁금하실 만한 것들',
  faq=[('고객이 예약하려면 앱을 설치해야 하나요?','아니요. 고객은 링크를 누르거나 QR 카드를 스캔해 브라우저에서 바로 예약할 수 있습니다. 설치도, 계정 가입도 필요 없습니다. 웹 예약은 모두 매장이 확인해야 확정되며, 이미 앱이 있는 고객은 앱에서 바로 열립니다.'),
       ('매장에서 대신 예약을 넣을 수 있나요?','가능합니다. 전화·방문 예약도 온라인 예약과 같은 캘린더에 들어가고 통계와 고객 기록에도 반영됩니다.'),
       ('고객이 시간을 바꾸고 싶어 하면요?','양쪽 모두 취소 없이 일정을 변경할 수 있어 원래 예약이 그대로 남고 수치도 정확하게 유지됩니다.'),
       ('수수료를 받거나 결제를 대신 보관하나요?','아니요. 고객이 매장에 직접 결제하므로 저희가 자금을 취급하지 않으며 수수료도 없습니다.'),
       ('이미 예약 플랫폼에 등록되어 있는데 함께 써도 되나요?','됩니다. 플랫폼은 신규 고객을, BookingYou는 단골을 포함한 모든 예약 관리를 맡습니다. 역할이 다르므로 병행할 수 있습니다.')],
  dl_note='내려받은 뒤 이메일로 가입하면 바로 설정을 시작할 수 있습니다.',
)
E['ms'] = dict(
  badge_apple='apple-ms-my.svg', badge_google='google-ms.png',
  p_lead='Telefon, mesej dan buku catatan datang serentak. Bagi kedai yang dijalankan seorang atau berdua, tiga perkara di bawah hampir pasti berlaku.',
  s_lead='Pelanggan memilih masa sendiri, jadi anda tidak perlu berhenti di tengah kerja untuk menjawab telefon. Tempahan dari semua saluran masuk ke satu kalendar.',
  d_extra='Contohnya: Selasa jam 3 petang biasanya lapang, jadi sahkan serta-merta. Malam Sabtu waktu paling sibuk, jadi tunggu kelulusan anda. Kedai yang sama, peraturan berbeza ikut waktu.',
  w_lead='Jika perniagaan anda ialah "pelanggan menempah masa dan datang", aliran ini sesuai. Berikut kategori yang sudah menggunakannya; kedai dengan corak serupa juga sama.',
  st_chip='Cara bermula', st_h2='Tiga langkah ke tempahan pertama anda',
  st_items=[('Daftar sebagai kedai','Buka akaun dengan e-mel, kemudian pilih kategori dan lokasi kedai anda.'),
            ('Masukkan perkhidmatan dan waktu operasi','Tetapkan tempoh dan harga bagi setiap perkhidmatan, serta waktu operasi mingguan. Hari tutup dan slot simpanan boleh diubah bila-bila masa.'),
            ('Beri kad QR atau pautan kepada pelanggan','Kad QR untuk dicetak dan pautan tempahan dijana serta-merta — tampal di kedai, letak di media sosial atau cetak pada kad nama.')],
  faq_chip='Soalan lazim', faq_h2='Mungkin anda tertanya',
  faq=[('Perlukah pelanggan memasang aplikasi untuk menempah?','Tidak. Pelanggan mengetik pautan anda atau mengimbas kad QR dan terus menempah dalam pelayar — tanpa pemasangan dan tanpa akaun. Setiap tempahan web menunggu pengesahan anda, dan pelanggan yang sudah ada aplikasi akan terus masuk ke aplikasi.'),
       ('Bolehkah saya memasukkan tempahan bagi pihak pelanggan?','Boleh. Tempahan telefon dan walk-in masuk ke kalendar yang sama dan dikira dalam statistik serta rekod pelanggan.'),
       ('Bagaimana jika pelanggan mahu tukar masa?','Kedua-dua pihak boleh menukar masa tanpa membatalkan, jadi tempahan asal kekal dan angka anda tetap tepat.'),
       ('Adakah anda mengambil komisen atau memegang wang saya?','Tidak. Pelanggan membayar terus kepada kedai anda. Kami tidak mengendalikan wang, jadi tiada komisen.'),
       ('Saya sudah tersenarai di portal tempahan. Boleh guna sekali?','Boleh. Portal membawa pelanggan baharu; BookingYou menguruskan semua tempahan termasuk pelanggan tetap. Kedua-duanya boleh digunakan bersama.')],
  dl_note='Muat turun, daftar dengan e-mel anda, dan anda boleh mula menyediakannya.',
)
E['th'] = dict(
  badge_apple='apple-th-th.svg', badge_google='google-th.png',
  p_lead='โทรศัพท์ ข้อความ และสมุดจดมาพร้อมกัน ร้านที่ทำกันหนึ่งถึงสองคนแทบทุกร้านเจอสามเรื่องนี้',
  s_lead='ลูกค้าเลือกเวลาเอง เจ้าของร้านจึงไม่ต้องหยุดงานตรงหน้ามารับสาย การจองจากทุกช่องทางมารวมอยู่ในปฏิทินเดียว',
  d_extra='ตัวอย่างเช่น บ่ายสามวันอังคารมักพอรับได้ ก็ตั้งให้ยืนยันทันที ส่วนคืนวันเสาร์เป็นช่วงที่แน่นที่สุด ก็ตั้งให้รอเจ้าของร้านอนุมัติ ร้านเดียวกันแต่คนละกฎตามช่วงเวลา',
  w_lead='ถ้าธุรกิจของคุณคือ "ลูกค้าจองเวลาแล้วมาที่ร้าน" ขั้นตอนนี้ใช้ได้เลย ด้านล่างคือประเภทร้านที่ใช้อยู่แล้ว ร้านที่มีรูปแบบคล้ายกันก็ใช้ได้เช่นกัน',
  st_chip='เริ่มอย่างไร', st_h2='สามขั้นตอนสู่การจองครั้งแรก',
  st_items=[('สมัครเป็นร้านค้า','เปิดบัญชีด้วยอีเมล แล้วเลือกประเภทและที่ตั้งของร้าน'),
            ('ใส่บริการและเวลาทำการ','กำหนดระยะเวลาและราคาของแต่ละบริการ พร้อมตั้งเวลาทำการรายสัปดาห์ วันหยุดและช่วงเวลาที่กันไว้แก้ไขได้ตลอด'),
            ('ส่งการ์ด QR หรือลิงก์ให้ลูกค้า','ระบบสร้างการ์ด QR สำหรับพิมพ์และลิงก์จองให้ทันที ติดที่ร้าน ใส่ในโซเชียล หรือพิมพ์บนนามบัตรก็ได้')],
  faq_chip='คำถามที่พบบ่อย', faq_h2='คำถามที่มักได้รับ',
  faq=[('ลูกค้าต้องติดตั้งแอปก่อนจองไหม','ไม่ต้อง ลูกค้าแตะลิงก์หรือสแกนการ์ด QR ของคุณ แล้วจองผ่านเบราว์เซอร์ได้ทันที ไม่ต้องติดตั้งและไม่ต้องสมัครบัญชี การจองผ่านเว็บทุกรายการต้องรอคุณยืนยัน ส่วนลูกค้าที่มีแอปอยู่แล้วจะเปิดในแอปโดยตรง'),
       ('ร้านใส่การจองแทนลูกค้าได้ไหม','ได้ การจองทางโทรศัพท์และหน้าร้านจะอยู่ในปฏิทินเดียวกับการจองออนไลน์ และนับรวมในสถิติและประวัติลูกค้า'),
       ('ถ้าลูกค้าขอเปลี่ยนเวลาล่ะ','ทั้งสองฝ่ายเลื่อนนัดได้โดยไม่ต้องยกเลิก การจองเดิมจึงยังอยู่ และตัวเลขก็ตรงกับความจริง'),
       ('มีการหักค่าคอมมิชชั่นหรือถือเงินลูกค้าไหม','ไม่มี ลูกค้าจ่ายให้ร้านโดยตรง เราไม่ได้ถือเงิน จึงไม่มีค่าคอมมิชชั่น'),
       ('ร้านอยู่บนแพลตฟอร์มจองอื่นอยู่แล้ว ใช้ร่วมกันได้ไหม','ได้ แพลตฟอร์มช่วยหาลูกค้าใหม่ ส่วน BookingYou ดูแลการจองทั้งหมดรวมถึงลูกค้าประจำ ใช้ควบคู่กันได้')],
  dl_note='ดาวน์โหลดแล้วสมัครด้วยอีเมล ก็เริ่มตั้งค่าได้ทันที',
)
E['vi'] = dict(
  badge_apple='apple-vi-vn.svg', badge_google='google-vi.png',
  p_lead='Điện thoại, tin nhắn và sổ giấy ập đến cùng lúc. Tiệm do một hai người làm gần như đều gặp ba chuyện dưới đây.',
  s_lead='Khách tự chọn giờ nên bạn không phải ngưng tay giữa chừng để nghe máy. Lịch đặt từ mọi kênh đều về chung một lịch.',
  d_extra='Ví dụ: 3 giờ chiều thứ Ba thường còn chỗ nên để xác nhận ngay; tối thứ Bảy là khung giờ đông nhất nên để bạn duyệt. Cùng một tiệm, mỗi khung giờ một quy tắc.',
  w_lead='Nếu công việc của bạn là "khách đặt giờ rồi tới", quy trình này dùng được ngay. Dưới đây là các ngành đang dùng; tiệm có cách vận hành tương tự cũng vậy.',
  st_chip='Bắt đầu thế nào', st_h2='Ba bước tới lượt đặt đầu tiên',
  st_items=[('Đăng ký làm chủ tiệm','Tạo tài khoản bằng email, rồi chọn ngành nghề và nơi đặt tiệm.'),
            ('Nhập dịch vụ và giờ mở cửa','Đặt thời lượng và giá cho từng dịch vụ, cài giờ mở cửa theo tuần. Ngày nghỉ và khung giờ giữ chỗ có thể sửa bất cứ lúc nào.'),
            ('Đưa thẻ QR hoặc liên kết cho khách','Thẻ QR để in và liên kết đặt lịch được tạo ngay — dán ở tiệm, để trên mạng xã hội hoặc in lên danh thiếp.')],
  faq_chip='Câu hỏi thường gặp', faq_h2='Có thể bạn đang thắc mắc',
  faq=[('Khách có cần cài ứng dụng mới đặt được không?','Không cần. Khách chạm vào liên kết hoặc quét thẻ QR của bạn rồi đặt lịch ngay trên trình duyệt — không cần cài đặt, không cần tài khoản. Mọi lịch đặt trên web đều chờ bạn xác nhận, còn khách đã có ứng dụng sẽ mở thẳng trong ứng dụng.'),
       ('Tôi có thể đặt hộ khách không?','Được. Lịch gọi điện và khách tới trực tiếp đều vào chung lịch với đặt online, đồng thời được tính vào thống kê và hồ sơ khách.'),
       ('Nếu khách muốn đổi giờ thì sao?','Cả hai bên đều đổi được mà không cần huỷ, nên lượt đặt ban đầu vẫn còn và số liệu vẫn đúng thực tế.'),
       ('Có thu hoa hồng hay giữ tiền của khách không?','Không. Khách trả trực tiếp cho tiệm. Chúng tôi không giữ tiền nên cũng không có hoa hồng.'),
       ('Tiệm tôi đã có trên nền tảng đặt lịch khác, dùng chung được không?','Được. Nền tảng mang khách mới đến; BookingYou quản lý mọi lượt đặt kể cả khách quen. Hai bên bổ trợ cho nhau.')],
  dl_note='Tải về, đăng ký bằng email là có thể bắt đầu thiết lập.',
)
