# 每個語言一份文案。en / ja 用返繁中投資者簡報同日文版簡報嘅正式用語。
L = {}

L['zh-HK'] = dict(
  lang='zh-Hant', name='繁體中文',
  title='BookingYou — 為獨立小店而設的預約前台',
  desc='BookingYou：客人自助預約，店主管理全日。美容院、理髮、美甲、物理治療等預約制小店，一個 App 收晒所有預約。',
  nav=['問題','方案','差異','服務對象','收費'],
  hero_tag='預約制小店 · 美容 · 理髮 · 美甲 · 物理治療',
  hero_sub='為獨立小店而設的預約前台。客人自助預約，店主管理全日。',
  cta1='免費開始', cta2='睇下點運作', hero_foot='已於 App Store 及 Google Play 上架',
  p_chip='問題', p_h2='小店至今仍以人手處理預約',
  p_items=[('服務期間電話響起','一人店主要停手接聽預約，營業時間後的查詢則容易錯過。'),
           ('預約分散各處','電話、通訊軟件、社交平台私訊加上紙本記錄，無法一眼看清整天安排。'),
           ('熟客都要經平台','光顧開的客人再約，一樣要經第三方平台，而平台按單收費。')],
  illus='示意圖',
  s_chip='方案', s_h2='一個 App：客人自助預約，店主管理全日',
  s_items=[('客人 24 小時預約','透過店舖連結或印刷 QR 卡'),('電話及上門預約','與網上預約記入同一個日曆'),
           ('改期毋須取消','自動提醒減少缺席'),('休息日、保留時段及課堂人數上限','令日曆與實際營運一致')],
  s_cap1='商戶主頁', s_cap2='可印刷的 QR 預約卡',
  d_chip='差異', d_h2='店主自行決定哪些時段自動確認',
  d_lead='App 預約可按時段設定即時確認或商戶審批；網頁預約一律要商戶確認先成立。',
  d_boxT='規則在伺服器執行，不只在 App 內',
  d_boxB='時段、人數、休息日及審批規則均在資料庫檢查，即使改動客戶端亦無法繞過。',
  d_cap='按時段設定是否需要審批',
  w_chip='服務對象', w_h2='同一套工具，適用於各類預約制小店',
  w_inds=['美容院','理髮店','美甲店','物理治療','寵物美容','私人補習'],
  m_chip='宣傳', m_h2='店舖可直接用的宣傳素材',
  m_lead='加入之後即有可印刷的 QR 卡同社交平台貼文圖，唔使自己搵設計。',
  m_caps=['商戶及客人總覽','三步完成預約','QR 預約連結'],
  y_chip='吉祥物', y_h2='U仔',
  y_lead='一本會走會跳的座枱日曆。日本叫「ユーくん」，英文 Yu-kun，台灣及內地叫小U。見到佢，就知道呢度約得到。',
  pl_chip='收費模式', pl_h2='基本功能永久免費，專業版規劃中',
  pl_core_badge='永久免費', pl_core='基本版',
  pl_core_items=['預約頁及 QR 卡','日曆、代客預約、改期','提醒及審批規則','基本功能免月費'],
  pl_pro_badge='規劃中', pl_pro='專業版',
  pl_pro_items=['為成長中店舖而設的進階功能','專業版尚未推出，定價未定'],
  pl_note='不經手款項：客人直接向店舖付款，因此不收佣金，亦無資金流經平台。',
  f_h2='今日就開始收預約', f_sub='BookingYou：於 App Store 或 Google Play 搜尋',
  foot_privacy='私隱政策', foot_terms='服務條款', foot_contact='聯絡我們',
)

L['en'] = dict(
  lang='en', name='English',
  title='BookingYou — The booking desk for independent service shops',
  desc='BookingYou: customers book themselves, the shop runs its day. One app for salons, barbers, nail studios, physio and other appointment-based shops.',
  nav=['Problem','Solution','What’s different','Who we serve','Pricing'],
  hero_tag='Appointment-based shops · Beauty · Barber · Nails · Physio',
  hero_sub='The booking desk for independent service shops. Customers book, the shop runs its day.',
  cta1='Start free', cta2='See how it works', hero_foot='Live on the App Store and Google Play',
  p_chip='The problem', p_h2='Small shops still run bookings by hand',
  p_items=[('The phone rings mid-treatment','Solo owners stop work to take bookings — and miss the ones that arrive after hours.'),
           ('Bookings are scattered','Phone, messaging apps, social media DMs and a paper book. No single view of the day.'),
           ('Even your regulars go through a portal','A customer who already knows you books through a third party that charges per booking.')],
  illus='Illustration',
  s_chip='The solution', s_h2='One app: customers book, the shop runs its day',
  s_items=[('Customers book 24/7','from the shop’s link or printed QR card'),('Phone and walk-in bookings','go into the same calendar as online ones'),
           ('Reschedule without cancelling','and automatic reminders reduce no-shows'),('Closed days, reserved slots, class capacity','so the calendar matches the real shop')],
  s_cap1='Merchant dashboard', s_cap2='Printable QR booking card',
  d_chip='What’s different', d_h2='The owner decides which hours book themselves',
  d_lead='In-app bookings follow the time slot’s instant-confirmation or merchant-approval setting. Web bookings always require merchant confirmation.',
  d_boxT='Enforced on the server, not only in the app',
  d_boxB='Timing, capacity, closed days and approval rules are checked in the database, so a modified client cannot book around them.',
  d_cap='Per-window approval setting',
  w_chip='Who we serve', w_h2='One tool for every appointment-based shop',
  w_inds=['Hair salon','Barber','Nail studio','Physio','Pet grooming','Tutoring'],
  m_chip='Brand', m_h2='Ready-made materials for your shop',
  m_lead='Printable QR cards and social posts come with the app — no designer needed.',
  m_caps=['Merchant and customer overview','Three-step booking','QR booking link'],
  y_chip='Mascot', y_h2='Yu-kun',
  y_lead='A living desk calendar. ユーくん in Japan, Yu-kun in English, U仔 in Hong Kong, 小U in Taiwan and the Mainland. Where you see him, you can book.',
  pl_chip='Pricing', pl_h2='Core features free forever; Pro is planned',
  pl_core_badge='Free, permanently', pl_core='Core',
  pl_core_items=['Booking page and QR card','Calendar, walk-in bookings, rescheduling','Reminders and approval rules','No monthly fee for core features'],
  pl_pro_badge='Planned', pl_pro='Pro',
  pl_pro_items=['Advanced tools for growing shops','Pro is not available yet; pricing is undecided'],
  pl_note='No payment handling: customers pay the shop directly, so there is no commission and no money in transit.',
  f_h2='Take your first booking today', f_sub='BookingYou — search it on the App Store or Google Play',
  foot_privacy='Privacy Policy', foot_terms='Terms of Service', foot_contact='Contact us',
)

L['ja'] = dict(
  lang='ja', name='日本語',
  title='BookingYou — 個人経営のサービス店のための予約受付',
  desc='BookingYou：お客様は自分で予約、お店は1日を管理。美容室・理容室・ネイル・整体など、予約制の小さなお店のための予約アプリ。',
  nav=['課題','解決策','独自性','対象業種','料金'],
  hero_tag='予約制のお店 · 美容 · 理容 · ネイル · 整体',
  hero_sub='個人経営のサービス店のための予約受付。お客様は自分で予約、お店は1日を管理。',
  cta1='無料ではじめる', cta2='使い方を見る', hero_foot='App Store・Google Playで配信中',
  p_chip='課題', p_h2='小さなお店の予約は、いまも手作業',
  p_items=[('施術中に電話が鳴る','一人で営むオーナーは手を止めて予約を受け、営業時間外の問い合わせは取りこぼしがちです。'),
           ('予約がバラバラ','電話、メッセージアプリ、SNSのDM、紙の台帳。1日の予定をひと目で把握できません。'),
           ('常連の予約も予約サイト経由','すでに知っているお客様の予約にも、予約サイトの手数料がかかります。')],
  illus='イメージ',
  s_chip='解決策', s_h2='ひとつのアプリで、お客様は予約、お店は1日を管理',
  s_items=[('24時間いつでも予約','お店のリンクや印刷したQRカードから'),('電話・来店の予約も','ネット予約と同じカレンダーに記録'),
           ('キャンセルせずに日時変更','自動リマインダーで無断キャンセルを減らす'),('定休日・予約枠の確保・定員設定','カレンダーを実際のお店に合わせる')],
  s_cap1='店舗ダッシュボード', s_cap2='印刷用QR予約カード',
  d_chip='独自性', d_h2='どの時間帯を自動確定にするか、オーナーが決める',
  d_lead='アプリ内予約は時間帯ごとの即時確定・店舗承認の設定に従います。ウェブ予約は必ず店舗の確認後に確定します。',
  d_boxT='ルールはアプリだけでなくサーバーで実行',
  d_boxB='時間、定員、定休日、承認ルールはデータベースで検証されるため、改変したアプリでも回避できません。',
  d_cap='時間帯ごとの承認設定',
  w_chip='対象業種', w_h2='予約制の小さなお店なら、同じツールで',
  w_inds=['美容室','理容室','ネイル','整体','トリミング','家庭教師'],
  m_chip='ブランド', m_h2='お店がそのまま使える販促素材',
  m_lead='印刷用QRカードとSNS投稿用デザインが最初から揃っています。',
  m_caps=['店舗とお客様向けの概要','3ステップで予約','QR予約リンク'],
  y_chip='マスコット', y_h2='ユーくん',
  y_lead='歩いて跳ねる卓上カレンダー。日本では「ユーくん」、英語ではYu-kun、香港ではU仔。この子がいるお店は、予約できます。',
  pl_chip='料金', pl_h2='基本機能はずっと無料。Proは計画中',
  pl_core_badge='ずっと無料', pl_core='ベーシック',
  pl_core_items=['予約ページとQRカード','カレンダー、代理予約、日時変更','リマインダーと承認ルール','基本機能は月額料金なし'],
  pl_pro_badge='計画中', pl_pro='プロ',
  pl_pro_items=['成長する店舗向けの上位機能','Proは未提供。料金は未定です'],
  pl_note='決済は扱いません。お客様はお店に直接お支払いいただくため、手数料も資金の預かりも発生しません。',
  f_h2='今日から予約を受けはじめる', f_sub='BookingYou — App Store・Google Playで検索',
  foot_privacy='プライバシーポリシー', foot_terms='利用規約', foot_contact='お問い合わせ',
)

L['zh-CN'] = dict(
  lang='zh-Hans', name='简体中文',
  title='BookingYou — 为独立小店打造的预约前台',
  desc='BookingYou：客人自助预约，店主管理全天。美容院、理发、美甲、理疗等预约制小店，一个 App 收齐所有预约。',
  nav=['问题','方案','差异','服务对象','收费'],
  hero_tag='预约制小店 · 美容 · 理发 · 美甲 · 理疗',
  hero_sub='为独立小店打造的预约前台。客人自助预约，店主管理全天。',
  cta1='免费开始', cta2='看看怎么用', hero_foot='已在 App Store 及 Google Play 上架',
  p_chip='问题', p_h2='小店至今仍靠人工处理预约',
  p_items=[('服务过程中电话响起','一人经营的店主要停下手上的工作接听预约，营业时间之后的咨询容易错过。'),
           ('预约分散各处','电话、即时通讯、社交平台私信加上纸质记录，无法一眼看清全天安排。'),
           ('老客户也要经平台','已经熟悉的客人再次预约，同样要经第三方平台，而平台按单收费。')],
  illus='示意图',
  s_chip='方案', s_h2='一个 App：客人自助预约，店主管理全天',
  s_items=[('客人 24 小时预约','通过店铺链接或印制的二维码卡'),('电话及到店预约','与线上预约记入同一个日历'),
           ('改期无需取消','自动提醒减少爽约'),('休息日、保留时段及课堂人数上限','让日历与实际经营一致')],
  s_cap1='商户主页', s_cap2='可打印的二维码预约卡',
  d_chip='差异', d_h2='店主自行决定哪些时段自动确认',
  d_lead='App 预约按时段设置即时确认或商户审核；网页预约均需商户确认后才成立。',
  d_boxT='规则在服务器执行，不只在 App 内',
  d_boxB='时段、人数、休息日及审核规则均在数据库校验，即使改动客户端也无法绕过。',
  d_cap='按时段设置是否需要审核',
  w_chip='服务对象', w_h2='同一套工具，适用于各类预约制小店',
  w_inds=['美容院','理发店','美甲店','理疗','宠物美容','私人辅导'],
  m_chip='宣传', m_h2='店铺可直接使用的宣传素材',
  m_lead='加入之后即有可打印的二维码卡和社交平台配图，无需另找设计。',
  m_caps=['商户及客人总览','三步完成预约','二维码预约链接'],
  y_chip='吉祥物', y_h2='小U',
  y_lead='一本会走会跳的台历。日本叫「ユーくん」，英文 Yu-kun，香港叫 U仔。看到它，就知道这里可以预约。',
  pl_chip='收费模式', pl_h2='基本功能永久免费，专业版规划中',
  pl_core_badge='永久免费', pl_core='基础版',
  pl_core_items=['预约页及二维码卡','日历、代客预约、改期','提醒及审核规则','基本功能免月费'],
  pl_pro_badge='规划中', pl_pro='专业版',
  pl_pro_items=['为成长中店铺而设的进阶功能','专业版尚未推出，价格未定'],
  pl_note='不经手款项：客人直接向店铺付款，因此不收佣金，也没有资金流经平台。',
  f_h2='今天就开始收预约', f_sub='BookingYou：在 App Store 或 Google Play 搜索',
  foot_privacy='隐私政策', foot_terms='服务条款', foot_contact='联系我们',
)

L['ko'] = dict(
  lang='ko', name='한국어',
  title='BookingYou — 소규모 개인 매장을 위한 예약 데스크',
  desc='BookingYou: 고객은 스스로 예약하고, 매장은 하루를 관리합니다. 미용실, 이발소, 네일, 물리치료 등 예약제 매장을 위한 앱.',
  nav=['문제','해결책','차별점','대상 업종','요금'],
  hero_tag='예약제 매장 · 미용 · 이발 · 네일 · 물리치료',
  hero_sub='소규모 개인 매장을 위한 예약 데스크. 고객은 스스로 예약하고, 매장은 하루를 관리합니다.',
  cta1='무료로 시작', cta2='사용 방법 보기', hero_foot='App Store 및 Google Play에서 이용 가능',
  p_chip='문제', p_h2='작은 매장의 예약은 아직도 수작업입니다',
  p_items=[('시술 중에 전화가 울립니다','혼자 운영하는 사장님은 하던 일을 멈추고 예약을 받아야 하고, 영업시간 이후 문의는 놓치기 쉽습니다.'),
           ('예약이 여기저기 흩어집니다','전화, 메신저, SNS 메시지에 종이 장부까지. 하루 일정을 한눈에 볼 수 없습니다.'),
           ('단골 예약도 플랫폼을 거칩니다','이미 아는 고객이 다시 예약해도 제3자 플랫폼을 거치고, 플랫폼은 건당 수수료를 받습니다.')],
  illus='이미지',
  s_chip='해결책', s_h2='하나의 앱으로 고객은 예약, 매장은 하루를 관리',
  s_items=[('고객은 24시간 예약','매장 링크나 인쇄한 QR 카드로'),('전화·방문 예약도','온라인 예약과 같은 캘린더에 기록'),
           ('취소 없이 일정 변경','자동 알림으로 노쇼를 줄입니다'),('휴무일·확보 시간대·정원 설정','캘린더를 실제 운영에 맞춥니다')],
  s_cap1='매장 대시보드', s_cap2='인쇄용 QR 예약 카드',
  d_chip='차별점', d_h2='어느 시간대를 자동 확정할지 사장님이 정합니다',
  d_lead='앱 예약은 시간대별 즉시 확정 또는 매장 승인 설정을 따릅니다. 웹 예약은 항상 매장 확인 후 확정됩니다.',
  d_boxT='규칙은 앱이 아니라 서버에서 실행됩니다',
  d_boxB='시간, 정원, 휴무일, 승인 규칙은 데이터베이스에서 검증되므로 변조된 앱으로도 우회할 수 없습니다.',
  d_cap='시간대별 승인 설정',
  w_chip='대상 업종', w_h2='예약제 매장이라면 같은 도구로',
  w_inds=['미용실','이발소','네일숍','물리치료','반려동물 미용','개인 과외'],
  m_chip='브랜드', m_h2='매장이 바로 쓰는 홍보 자료',
  m_lead='인쇄용 QR 카드와 SNS 게시용 이미지가 처음부터 준비되어 있습니다.',
  m_caps=['매장 및 고객 개요','3단계 예약','QR 예약 링크'],
  y_chip='마스코트', y_h2='Yu-kun',
  y_lead='걸어 다니는 탁상 달력. 일본에서는 ユーくん, 영어로는 Yu-kun, 홍콩에서는 U仔라고 부릅니다. 이 친구가 있는 곳은 예약할 수 있습니다.',
  pl_chip='요금', pl_h2='기본 기능은 계속 무료, Pro는 기획 중',
  pl_core_badge='영구 무료', pl_core='베이직',
  pl_core_items=['예약 페이지와 QR 카드','캘린더, 대리 예약, 일정 변경','알림 및 승인 규칙','기본 기능 월 이용료 없음'],
  pl_pro_badge='준비 중', pl_pro='프로',
  pl_pro_items=['성장하는 매장을 위한 고급 기능','Pro는 아직 출시되지 않았으며 가격은 미정입니다'],
  pl_note='결제는 취급하지 않습니다. 고객이 매장에 직접 결제하므로 수수료도, 예치금도 없습니다.',
  f_h2='오늘 첫 예약을 받아보세요', f_sub='BookingYou — App Store 또는 Google Play에서 검색',
  foot_privacy='개인정보처리방침', foot_terms='이용약관', foot_contact='문의하기',
)

L['ms'] = dict(
  lang='ms', name='Bahasa Melayu',
  title='BookingYou — Kaunter tempahan untuk kedai perkhidmatan kecil',
  desc='BookingYou: pelanggan menempah sendiri, kedai menguruskan hari. Satu aplikasi untuk salon, kedai gunting rambut, nail studio, fisioterapi dan kedai berasaskan temu janji.',
  nav=['Masalah','Penyelesaian','Apa yang berbeza','Untuk siapa','Harga'],
  hero_tag='Kedai temu janji · Kecantikan · Gunting rambut · Kuku · Fisioterapi',
  hero_sub='Kaunter tempahan untuk kedai perkhidmatan kecil. Pelanggan menempah sendiri, kedai menguruskan harinya.',
  cta1='Mula percuma', cta2='Lihat cara ia berfungsi', hero_foot='Sudah ada di App Store dan Google Play',
  p_chip='Masalah', p_h2='Kedai kecil masih uruskan tempahan secara manual',
  p_items=[('Telefon berdering semasa rawatan','Pemilik yang bekerja sendirian terpaksa berhenti untuk menjawab, dan pertanyaan selepas waktu operasi mudah terlepas.'),
           ('Tempahan bertaburan','Telefon, aplikasi pesanan, DM media sosial dan buku catatan. Tiada satu paparan untuk seluruh hari.'),
           ('Pelanggan tetap pun melalui portal','Pelanggan yang sudah kenal anda menempah melalui pihak ketiga yang mengenakan caj bagi setiap tempahan.')],
  illus='Ilustrasi',
  s_chip='Penyelesaian', s_h2='Satu aplikasi: pelanggan menempah, kedai menguruskan harinya',
  s_items=[('Pelanggan menempah 24 jam','melalui pautan kedai atau kad QR bercetak'),('Tempahan telefon dan walk-in','masuk ke kalendar yang sama'),
           ('Tukar masa tanpa membatalkan','peringatan automatik mengurangkan ketidakhadiran'),('Hari tutup, slot simpanan, had kelas','supaya kalendar sepadan dengan operasi sebenar')],
  s_cap1='Papan pemuka kedai', s_cap2='Kad tempahan QR untuk dicetak',
  d_chip='Apa yang berbeza', d_h2='Pemilik tentukan waktu mana yang disahkan automatik',
  d_lead='Tempahan dalam aplikasi mengikut tetapan slot: pengesahan segera atau kelulusan peniaga. Tempahan web sentiasa memerlukan pengesahan peniaga.',
  d_boxT='Dikuatkuasakan pada pelayan, bukan hanya dalam aplikasi',
  d_boxB='Masa, kapasiti, hari tutup dan peraturan kelulusan disemak dalam pangkalan data, jadi aplikasi yang diubah suai tidak boleh memintasnya.',
  d_cap='Tetapan kelulusan mengikut waktu',
  w_chip='Untuk siapa', w_h2='Satu alat untuk semua kedai berasaskan temu janji',
  w_inds=['Salon rambut','Kedai gunting','Studio kuku','Fisioterapi','Dandanan haiwan','Tuisyen'],
  m_chip='Jenama', m_h2='Bahan promosi sedia guna untuk kedai anda',
  m_lead='Kad QR untuk dicetak dan grafik media sosial disediakan sekali — tidak perlu cari pereka.',
  m_caps=['Gambaran kedai dan pelanggan','Tempahan tiga langkah','Pautan tempahan QR'],
  y_chip='Maskot', y_h2='Yu-kun',
  y_lead='Kalendar meja yang hidup. ユーくん di Jepun, Yu-kun dalam bahasa Inggeris, U仔 di Hong Kong. Di mana ada dia, di situ boleh menempah.',
  pl_chip='Harga', pl_h2='Ciri asas percuma selamanya; Pro dalam perancangan',
  pl_core_badge='Percuma selamanya', pl_core='Asas',
  pl_core_items=['Halaman tempahan dan kad QR','Kalendar, tempahan bagi pihak pelanggan, tukar masa','Peringatan dan peraturan kelulusan','Tiada yuran bulanan untuk ciri asas'],
  pl_pro_badge='Dalam perancangan', pl_pro='Pro',
  pl_pro_items=['Ciri lanjutan untuk kedai yang berkembang','Pro belum tersedia; harga belum ditetapkan'],
  pl_note='Kami tidak mengendalikan pembayaran: pelanggan membayar terus kepada kedai, jadi tiada komisen dan tiada wang melalui platform.',
  f_h2='Terima tempahan pertama anda hari ini', f_sub='BookingYou — cari di App Store atau Google Play',
  foot_privacy='Dasar Privasi', foot_terms='Terma Perkhidmatan', foot_contact='Hubungi kami',
)

L['th'] = dict(
  lang='th', name='ไทย',
  title='BookingYou — เคาน์เตอร์รับจองสำหรับร้านเล็ก ๆ',
  desc='BookingYou: ลูกค้าจองเอง ร้านจัดการทั้งวัน แอปเดียวสำหรับร้านทำผม ร้านตัดผม ร้านทำเล็บ กายภาพบำบัด และร้านที่รับจองล่วงหน้า',
  nav=['ปัญหา','ทางออก','จุดต่าง','เหมาะกับใคร','ราคา'],
  hero_tag='ร้านรับจองล่วงหน้า · ความงาม · ตัดผม · ทำเล็บ · กายภาพบำบัด',
  hero_sub='เคาน์เตอร์รับจองสำหรับร้านเล็ก ๆ ลูกค้าจองเอง ร้านจัดการทั้งวัน',
  cta1='เริ่มใช้ฟรี', cta2='ดูวิธีใช้งาน', hero_foot='ดาวน์โหลดได้แล้วบน App Store และ Google Play',
  p_chip='ปัญหา', p_h2='ร้านเล็ก ๆ ยังรับจองด้วยมือ',
  p_items=[('โทรศัพท์ดังระหว่างให้บริการ','เจ้าของร้านคนเดียวต้องหยุดงานตรงหน้ามารับจอง ส่วนคำถามหลังเวลาทำการก็มักตกหล่น'),
           ('การจองกระจัดกระจาย','โทรศัพท์ แอปแชท ข้อความในโซเชียล และสมุดจด ไม่มีที่ไหนเห็นทั้งวันในหน้าเดียว'),
           ('ลูกค้าประจำก็ยังต้องผ่านแพลตฟอร์ม','ลูกค้าที่รู้จักร้านอยู่แล้วกลับต้องจองผ่านคนกลางที่คิดค่าธรรมเนียมต่อครั้ง')],
  illus='ภาพประกอบ',
  s_chip='ทางออก', s_h2='แอปเดียว ลูกค้าจองเอง ร้านจัดการทั้งวัน',
  s_items=[('ลูกค้าจองได้ตลอด 24 ชั่วโมง','ผ่านลิงก์ของร้านหรือการ์ด QR ที่พิมพ์ไว้'),('การจองทางโทรศัพท์และหน้าร้าน','บันทึกในปฏิทินเดียวกับการจองออนไลน์'),
           ('เลื่อนนัดได้โดยไม่ต้องยกเลิก','การแจ้งเตือนอัตโนมัติช่วยลดการไม่มาตามนัด'),('วันหยุด ช่วงเวลาที่กันไว้ และจำนวนคนต่อคลาส','ให้ปฏิทินตรงกับการทำงานจริง')],
  s_cap1='หน้าหลักของร้าน', s_cap2='การ์ด QR สำหรับพิมพ์',
  d_chip='จุดต่าง', d_h2='เจ้าของร้านเลือกเองว่าช่วงเวลาไหนยืนยันอัตโนมัติ',
  d_lead='การจองในแอปจะยืนยันอัตโนมัติหรือรอร้านอนุมัติตามการตั้งค่าแต่ละช่วงเวลา ส่วนการจองผ่านเว็บต้องรอร้านยืนยันทุกครั้ง',
  d_boxT='กฎทำงานที่เซิร์ฟเวอร์ ไม่ใช่แค่ในแอป',
  d_boxB='เวลา จำนวนคน วันหยุด และกฎการอนุมัติถูกตรวจในฐานข้อมูล แอปที่ถูกแก้ไขจึงข้ามไปไม่ได้',
  d_cap='ตั้งค่าการอนุมัติตามช่วงเวลา',
  w_chip='เหมาะกับใคร', w_h2='เครื่องมือเดียว ใช้ได้กับร้านที่รับจองทุกแบบ',
  w_inds=['ร้านทำผม','ร้านตัดผม','ร้านทำเล็บ','กายภาพบำบัด','ตัดขนสัตว์','ติวเตอร์'],
  m_chip='แบรนด์', m_h2='สื่อประชาสัมพันธ์ที่ร้านใช้ได้ทันที',
  m_lead='การ์ด QR สำหรับพิมพ์และภาพสำหรับโพสต์โซเชียลมีมาให้พร้อม ไม่ต้องหาคนออกแบบ',
  m_caps=['ภาพรวมสำหรับร้านและลูกค้า','จองใน 3 ขั้นตอน','ลิงก์จองแบบ QR'],
  y_chip='มาสคอต', y_h2='Yu-kun',
  y_lead='ปฏิทินตั้งโต๊ะที่เดินได้ ที่ญี่ปุ่นเรียก ユーくん ภาษาอังกฤษเรียก Yu-kun ที่ฮ่องกงเรียก U仔 เห็นเขาที่ไหน ที่นั่นจองได้',
  pl_chip='ราคา', pl_h2='ฟีเจอร์พื้นฐานฟรีตลอดไป ส่วน Pro อยู่ระหว่างวางแผน',
  pl_core_badge='ฟรีตลอด', pl_core='พื้นฐาน',
  pl_core_items=['หน้าจองและการ์ด QR','ปฏิทิน จองแทนลูกค้า เลื่อนนัด','การแจ้งเตือนและกฎการอนุมัติ','ฟีเจอร์พื้นฐานไม่มีค่ารายเดือน'],
  pl_pro_badge='อยู่ระหว่างวางแผน', pl_pro='โปร',
  pl_pro_items=['ฟังก์ชันขั้นสูงสำหรับร้านที่กำลังเติบโต','Pro ยังไม่เปิดให้บริการและยังไม่กำหนดราคา'],
  pl_note='เราไม่รับชำระเงินแทน ลูกค้าจ่ายให้ร้านโดยตรง จึงไม่มีค่าคอมมิชชั่นและไม่มีเงินผ่านแพลตฟอร์ม',
  f_h2='เริ่มรับจองครั้งแรกวันนี้', f_sub='BookingYou — ค้นหาใน App Store หรือ Google Play',
  foot_privacy='นโยบายความเป็นส่วนตัว', foot_terms='ข้อกำหนดการให้บริการ', foot_contact='ติดต่อเรา',
)

L['vi'] = dict(
  lang='vi', name='Tiếng Việt',
  title='BookingYou — Quầy nhận đặt lịch cho tiệm nhỏ',
  desc='BookingYou: khách tự đặt lịch, chủ tiệm quản lý cả ngày. Một ứng dụng cho salon, tiệm cắt tóc, tiệm nail, vật lý trị liệu và các tiệm nhận đặt hẹn.',
  nav=['Vấn đề','Giải pháp','Điểm khác biệt','Dành cho ai','Giá'],
  hero_tag='Tiệm nhận đặt hẹn · Làm đẹp · Cắt tóc · Nail · Vật lý trị liệu',
  hero_sub='Quầy nhận đặt lịch cho tiệm nhỏ. Khách tự đặt lịch, chủ tiệm quản lý cả ngày.',
  cta1='Bắt đầu miễn phí', cta2='Xem cách hoạt động', hero_foot='Đã có trên App Store và Google Play',
  p_chip='Vấn đề', p_h2='Tiệm nhỏ vẫn nhận đặt lịch thủ công',
  p_items=[('Điện thoại reo giữa lúc đang làm','Chủ tiệm làm một mình phải ngưng tay để nhận lịch, còn tin nhắn ngoài giờ thì dễ bỏ sót.'),
           ('Lịch đặt nằm rải rác','Điện thoại, ứng dụng nhắn tin, tin nhắn mạng xã hội và sổ giấy. Không có chỗ nào xem được cả ngày.'),
           ('Khách quen cũng phải qua nền tảng','Khách đã biết tiệm vẫn đặt qua bên thứ ba, và bên đó thu phí theo từng lượt đặt.')],
  illus='Ảnh minh hoạ',
  s_chip='Giải pháp', s_h2='Một ứng dụng: khách tự đặt, tiệm quản lý cả ngày',
  s_items=[('Khách đặt lịch 24/7','qua liên kết của tiệm hoặc thẻ QR đã in'),('Lịch gọi điện và khách tới trực tiếp','ghi vào cùng một lịch với đặt online'),
           ('Đổi giờ không cần huỷ','nhắc tự động giúp giảm khách không đến'),('Ngày nghỉ, khung giờ giữ chỗ, giới hạn lớp','để lịch khớp với hoạt động thật của tiệm')],
  s_cap1='Trang quản lý của tiệm', s_cap2='Thẻ đặt lịch QR để in',
  d_chip='Điểm khác biệt', d_h2='Chủ tiệm tự quyết khung giờ nào tự động xác nhận',
  d_lead='Đặt lịch trong ứng dụng tuân theo cài đặt xác nhận ngay hoặc chờ cửa hàng duyệt của từng khung giờ. Đặt lịch trên web luôn cần cửa hàng xác nhận.',
  d_boxT='Quy tắc chạy trên máy chủ, không chỉ trong ứng dụng',
  d_boxB='Thời gian, số chỗ, ngày nghỉ và quy tắc duyệt đều được kiểm tra trong cơ sở dữ liệu, nên ứng dụng bị sửa cũng không lách được.',
  d_cap='Cài đặt duyệt theo từng khung giờ',
  w_chip='Dành cho ai', w_h2='Một công cụ cho mọi tiệm nhận đặt hẹn',
  w_inds=['Salon tóc','Tiệm cắt tóc','Tiệm nail','Vật lý trị liệu','Chăm sóc thú cưng','Gia sư'],
  m_chip='Thương hiệu', m_h2='Bộ hình quảng bá dùng được ngay',
  m_lead='Thẻ QR để in và ảnh đăng mạng xã hội có sẵn từ đầu, không cần tìm người thiết kế.',
  m_caps=['Tổng quan cho tiệm và khách','Đặt lịch ba bước','Liên kết đặt lịch QR'],
  y_chip='Linh vật', y_h2='Yu-kun',
  y_lead='Một cuốn lịch để bàn biết đi. Ở Nhật gọi là ユーくん, tiếng Anh là Yu-kun, ở Hồng Kông gọi U仔. Thấy cậu ấy ở đâu là đặt lịch được ở đó.',
  pl_chip='Giá', pl_h2='Tính năng cơ bản miễn phí mãi mãi; Pro đang được lên kế hoạch',
  pl_core_badge='Miễn phí vĩnh viễn', pl_core='Cơ bản',
  pl_core_items=['Trang đặt lịch và thẻ QR','Lịch, đặt hộ khách, đổi giờ','Nhắc hẹn và quy tắc duyệt','Không thu phí tháng cho tính năng cơ bản'],
  pl_pro_badge='Đang lên kế hoạch', pl_pro='Pro',
  pl_pro_items=['Tính năng nâng cao cho tiệm đang phát triển','Pro chưa ra mắt; giá chưa được xác định'],
  pl_note='Chúng tôi không giữ tiền: khách trả trực tiếp cho tiệm, nên không có hoa hồng và không có dòng tiền qua nền tảng.',
  f_h2='Nhận lượt đặt đầu tiên ngay hôm nay', f_sub='BookingYou — tìm trên App Store hoặc Google Play',
  foot_privacy='Chính sách quyền riêng tư', foot_terms='Điều khoản dịch vụ', foot_contact='Liên hệ',
)
